/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as DiscoverIndexRouteImport } from './routes/discover.index'
import { Route as DiscoverBiologyOfAgingRouteImport } from './routes/discover.biology-of-aging'
import { Route as DiscoverHealthyLongevityRouteImport } from './routes/discover.healthy-longevity'
import { Route as DiscoverScientificMissionsRouteImport } from './routes/discover.scientific-missions'
import { Route as DiscoverWhatIsLongevityRouteImport } from './routes/discover.what-is-longevity'
import { Route as EcosystemIndexRouteImport } from './routes/ecosystem.index'
import { Route as EcosystemClinicalValidationRouteImport } from './routes/ecosystem.clinical-validation'
import { Route as EcosystemInvestmentCommercialRouteImport } from './routes/ecosystem.investment-commercial'
import { Route as EcosystemManufacturingSupplyRouteImport } from './routes/ecosystem.manufacturing-supply'
import { Route as EcosystemScienceDiscoveryRouteImport } from './routes/ecosystem.science-discovery'
import { Route as EcosystemUkDirectoryRouteImport } from './routes/ecosystem.uk-directory'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsEventsRouteImport } from './routes/insights.events'
import { Route as InsightsLongevityNewsRouteImport } from './routes/insights.longevity-news'
import { Route as InsightsResearchHighlightsRouteImport } from './routes/insights.research-highlights'
import { Route as PublicationsIndexRouteImport } from './routes/publications.index'
import { Route as PublicationsSlugRouteImport } from './routes/publications.$slug'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedMembersProfileIdRouteImport } from './routes/_authenticated/members.$profileId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiscoverRoute,
} as any)
const DiscoverBiologyOfAgingRoute = DiscoverBiologyOfAgingRouteImport.update({
  id: '/biology-of-aging',
  path: '/biology-of-aging',
  getParentRoute: () => DiscoverRoute,
} as any)
const DiscoverHealthyLongevityRoute =
  DiscoverHealthyLongevityRouteImport.update({
    id: '/healthy-longevity',
    path: '/healthy-longevity',
    getParentRoute: () => DiscoverRoute,
  } as any)
const DiscoverScientificMissionsRoute =
  DiscoverScientificMissionsRouteImport.update({
    id: '/scientific-missions',
    path: '/scientific-missions',
    getParentRoute: () => DiscoverRoute,
  } as any)
const DiscoverWhatIsLongevityRoute = DiscoverWhatIsLongevityRouteImport.update({
  id: '/what-is-longevity',
  path: '/what-is-longevity',
  getParentRoute: () => DiscoverRoute,
} as any)
const EcosystemIndexRoute = EcosystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcosystemRoute,
} as any)
const EcosystemClinicalValidationRoute =
  EcosystemClinicalValidationRouteImport.update({
    id: '/clinical-validation',
    path: '/clinical-validation',
    getParentRoute: () => EcosystemRoute,
  } as any)
const EcosystemInvestmentCommercialRoute =
  EcosystemInvestmentCommercialRouteImport.update({
    id: '/investment-commercial',
    path: '/investment-commercial',
    getParentRoute: () => EcosystemRoute,
  } as any)
const EcosystemManufacturingSupplyRoute =
  EcosystemManufacturingSupplyRouteImport.update({
    id: '/manufacturing-supply',
    path: '/manufacturing-supply',
    getParentRoute: () => EcosystemRoute,
  } as any)
const EcosystemScienceDiscoveryRoute =
  EcosystemScienceDiscoveryRouteImport.update({
    id: '/science-discovery',
    path: '/science-discovery',
    getParentRoute: () => EcosystemRoute,
  } as any)
const EcosystemUkDirectoryRoute = EcosystemUkDirectoryRouteImport.update({
  id: '/uk-directory',
  path: '/uk-directory',
  getParentRoute: () => EcosystemRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsEventsRoute = InsightsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsLongevityNewsRoute = InsightsLongevityNewsRouteImport.update({
  id: '/longevity-news',
  path: '/longevity-news',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsResearchHighlightsRoute =
  InsightsResearchHighlightsRouteImport.update({
    id: '/research-highlights',
    path: '/research-highlights',
    getParentRoute: () => InsightsRoute,
  } as any)
const PublicationsIndexRoute = PublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsSlugRoute = PublicationsSlugRouteImport.update({
  id: '/publications/$slug',
  path: '/publications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersProfileIdRoute =
  AuthenticatedMembersProfileIdRouteImport.update({
    id: '/members/$profileId',
    path: '/members/$profileId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/ecosystem': typeof EcosystemRouteWithChildren
  '/founder': typeof FounderRoute
  '/insights': typeof InsightsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/discover/biology-of-aging': typeof DiscoverBiologyOfAgingRoute
  '/discover/healthy-longevity': typeof DiscoverHealthyLongevityRoute
  '/discover/scientific-missions': typeof DiscoverScientificMissionsRoute
  '/discover/what-is-longevity': typeof DiscoverWhatIsLongevityRoute
  '/ecosystem/clinical-validation': typeof EcosystemClinicalValidationRoute
  '/ecosystem/investment-commercial': typeof EcosystemInvestmentCommercialRoute
  '/ecosystem/manufacturing-supply': typeof EcosystemManufacturingSupplyRoute
  '/ecosystem/science-discovery': typeof EcosystemScienceDiscoveryRoute
  '/ecosystem/uk-directory': typeof EcosystemUkDirectoryRoute
  '/insights/events': typeof InsightsEventsRoute
  '/insights/longevity-news': typeof InsightsLongevityNewsRoute
  '/insights/research-highlights': typeof InsightsResearchHighlightsRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/discover/': typeof DiscoverIndexRoute
  '/ecosystem/': typeof EcosystemIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/members/$profileId': typeof AuthenticatedMembersProfileIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/discover/biology-of-aging': typeof DiscoverBiologyOfAgingRoute
  '/discover/healthy-longevity': typeof DiscoverHealthyLongevityRoute
  '/discover/scientific-missions': typeof DiscoverScientificMissionsRoute
  '/discover/what-is-longevity': typeof DiscoverWhatIsLongevityRoute
  '/ecosystem/clinical-validation': typeof EcosystemClinicalValidationRoute
  '/ecosystem/investment-commercial': typeof EcosystemInvestmentCommercialRoute
  '/ecosystem/manufacturing-supply': typeof EcosystemManufacturingSupplyRoute
  '/ecosystem/science-discovery': typeof EcosystemScienceDiscoveryRoute
  '/ecosystem/uk-directory': typeof EcosystemUkDirectoryRoute
  '/insights/events': typeof InsightsEventsRoute
  '/insights/longevity-news': typeof InsightsLongevityNewsRoute
  '/insights/research-highlights': typeof InsightsResearchHighlightsRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/discover': typeof DiscoverIndexRoute
  '/ecosystem': typeof EcosystemIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/publications': typeof PublicationsIndexRoute
  '/members/$profileId': typeof AuthenticatedMembersProfileIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/ecosystem': typeof EcosystemRouteWithChildren
  '/founder': typeof FounderRoute
  '/insights': typeof InsightsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/discover/biology-of-aging': typeof DiscoverBiologyOfAgingRoute
  '/discover/healthy-longevity': typeof DiscoverHealthyLongevityRoute
  '/discover/scientific-missions': typeof DiscoverScientificMissionsRoute
  '/discover/what-is-longevity': typeof DiscoverWhatIsLongevityRoute
  '/ecosystem/clinical-validation': typeof EcosystemClinicalValidationRoute
  '/ecosystem/investment-commercial': typeof EcosystemInvestmentCommercialRoute
  '/ecosystem/manufacturing-supply': typeof EcosystemManufacturingSupplyRoute
  '/ecosystem/science-discovery': typeof EcosystemScienceDiscoveryRoute
  '/ecosystem/uk-directory': typeof EcosystemUkDirectoryRoute
  '/insights/events': typeof InsightsEventsRoute
  '/insights/longevity-news': typeof InsightsLongevityNewsRoute
  '/insights/research-highlights': typeof InsightsResearchHighlightsRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/discover/': typeof DiscoverIndexRoute
  '/ecosystem/': typeof EcosystemIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/_authenticated/members/$profileId': typeof AuthenticatedMembersProfileIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/discover'
    | '/ecosystem'
    | '/founder'
    | '/insights'
    | '/dashboard'
    | '/profile'
    | '/discover/biology-of-aging'
    | '/discover/healthy-longevity'
    | '/discover/scientific-missions'
    | '/discover/what-is-longevity'
    | '/ecosystem/clinical-validation'
    | '/ecosystem/investment-commercial'
    | '/ecosystem/manufacturing-supply'
    | '/ecosystem/science-discovery'
    | '/ecosystem/uk-directory'
    | '/insights/events'
    | '/insights/longevity-news'
    | '/insights/research-highlights'
    | '/publications/$slug'
    | '/discover/'
    | '/ecosystem/'
    | '/insights/'
    | '/publications/'
    | '/members/$profileId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/members/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/founder'
    | '/dashboard'
    | '/profile'
    | '/discover/biology-of-aging'
    | '/discover/healthy-longevity'
    | '/discover/scientific-missions'
    | '/discover/what-is-longevity'
    | '/ecosystem/clinical-validation'
    | '/ecosystem/investment-commercial'
    | '/ecosystem/manufacturing-supply'
    | '/ecosystem/science-discovery'
    | '/ecosystem/uk-directory'
    | '/insights/events'
    | '/insights/longevity-news'
    | '/insights/research-highlights'
    | '/publications/$slug'
    | '/discover'
    | '/ecosystem'
    | '/insights'
    | '/publications'
    | '/members/$profileId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/members'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/discover'
    | '/ecosystem'
    | '/founder'
    | '/insights'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/discover/biology-of-aging'
    | '/discover/healthy-longevity'
    | '/discover/scientific-missions'
    | '/discover/what-is-longevity'
    | '/ecosystem/clinical-validation'
    | '/ecosystem/investment-commercial'
    | '/ecosystem/manufacturing-supply'
    | '/ecosystem/science-discovery'
    | '/ecosystem/uk-directory'
    | '/insights/events'
    | '/insights/longevity-news'
    | '/insights/research-highlights'
    | '/publications/$slug'
    | '/discover/'
    | '/ecosystem/'
    | '/insights/'
    | '/publications/'
    | '/_authenticated/members/$profileId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/members/'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRouteWithChildren
  EcosystemRoute: typeof EcosystemRouteWithChildren
  FounderRoute: typeof FounderRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PublicationsSlugRoute: typeof PublicationsSlugRoute
  PublicationsIndexRoute: typeof PublicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/discover/': {
      id: '/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/discover/biology-of-aging': {
      id: '/discover/biology-of-aging'
      path: '/biology-of-aging'
      fullPath: '/discover/biology-of-aging'
      preLoaderRoute: typeof DiscoverBiologyOfAgingRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/discover/healthy-longevity': {
      id: '/discover/healthy-longevity'
      path: '/healthy-longevity'
      fullPath: '/discover/healthy-longevity'
      preLoaderRoute: typeof DiscoverHealthyLongevityRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/discover/scientific-missions': {
      id: '/discover/scientific-missions'
      path: '/scientific-missions'
      fullPath: '/discover/scientific-missions'
      preLoaderRoute: typeof DiscoverScientificMissionsRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/discover/what-is-longevity': {
      id: '/discover/what-is-longevity'
      path: '/what-is-longevity'
      fullPath: '/discover/what-is-longevity'
      preLoaderRoute: typeof DiscoverWhatIsLongevityRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/ecosystem/': {
      id: '/ecosystem/'
      path: '/'
      fullPath: '/ecosystem/'
      preLoaderRoute: typeof EcosystemIndexRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/clinical-validation': {
      id: '/ecosystem/clinical-validation'
      path: '/clinical-validation'
      fullPath: '/ecosystem/clinical-validation'
      preLoaderRoute: typeof EcosystemClinicalValidationRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/investment-commercial': {
      id: '/ecosystem/investment-commercial'
      path: '/investment-commercial'
      fullPath: '/ecosystem/investment-commercial'
      preLoaderRoute: typeof EcosystemInvestmentCommercialRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/manufacturing-supply': {
      id: '/ecosystem/manufacturing-supply'
      path: '/manufacturing-supply'
      fullPath: '/ecosystem/manufacturing-supply'
      preLoaderRoute: typeof EcosystemManufacturingSupplyRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/science-discovery': {
      id: '/ecosystem/science-discovery'
      path: '/science-discovery'
      fullPath: '/ecosystem/science-discovery'
      preLoaderRoute: typeof EcosystemScienceDiscoveryRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/uk-directory': {
      id: '/ecosystem/uk-directory'
      path: '/uk-directory'
      fullPath: '/ecosystem/uk-directory'
      preLoaderRoute: typeof EcosystemUkDirectoryRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/events': {
      id: '/insights/events'
      path: '/events'
      fullPath: '/insights/events'
      preLoaderRoute: typeof InsightsEventsRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/longevity-news': {
      id: '/insights/longevity-news'
      path: '/longevity-news'
      fullPath: '/insights/longevity-news'
      preLoaderRoute: typeof InsightsLongevityNewsRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/research-highlights': {
      id: '/insights/research-highlights'
      path: '/research-highlights'
      fullPath: '/insights/research-highlights'
      preLoaderRoute: typeof InsightsResearchHighlightsRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/publications/': {
      id: '/publications/'
      path: '/publications'
      fullPath: '/publications/'
      preLoaderRoute: typeof PublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$slug': {
      id: '/publications/$slug'
      path: '/publications/$slug'
      fullPath: '/publications/$slug'
      preLoaderRoute: typeof PublicationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$profileId': {
      id: '/_authenticated/members/$profileId'
      path: '/members/$profileId'
      fullPath: '/members/$profileId'
      preLoaderRoute: typeof AuthenticatedMembersProfileIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMembersProfileIdRoute: typeof AuthenticatedMembersProfileIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMembersProfileIdRoute: AuthenticatedMembersProfileIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DiscoverRouteChildren {
  DiscoverBiologyOfAgingRoute: typeof DiscoverBiologyOfAgingRoute
  DiscoverHealthyLongevityRoute: typeof DiscoverHealthyLongevityRoute
  DiscoverScientificMissionsRoute: typeof DiscoverScientificMissionsRoute
  DiscoverWhatIsLongevityRoute: typeof DiscoverWhatIsLongevityRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
}

const DiscoverRouteChildren: DiscoverRouteChildren = {
  DiscoverBiologyOfAgingRoute: DiscoverBiologyOfAgingRoute,
  DiscoverHealthyLongevityRoute: DiscoverHealthyLongevityRoute,
  DiscoverScientificMissionsRoute: DiscoverScientificMissionsRoute,
  DiscoverWhatIsLongevityRoute: DiscoverWhatIsLongevityRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
}

const DiscoverRouteWithChildren = DiscoverRoute._addFileChildren(
  DiscoverRouteChildren,
)

interface EcosystemRouteChildren {
  EcosystemClinicalValidationRoute: typeof EcosystemClinicalValidationRoute
  EcosystemInvestmentCommercialRoute: typeof EcosystemInvestmentCommercialRoute
  EcosystemManufacturingSupplyRoute: typeof EcosystemManufacturingSupplyRoute
  EcosystemScienceDiscoveryRoute: typeof EcosystemScienceDiscoveryRoute
  EcosystemUkDirectoryRoute: typeof EcosystemUkDirectoryRoute
  EcosystemIndexRoute: typeof EcosystemIndexRoute
}

const EcosystemRouteChildren: EcosystemRouteChildren = {
  EcosystemClinicalValidationRoute: EcosystemClinicalValidationRoute,
  EcosystemInvestmentCommercialRoute: EcosystemInvestmentCommercialRoute,
  EcosystemManufacturingSupplyRoute: EcosystemManufacturingSupplyRoute,
  EcosystemScienceDiscoveryRoute: EcosystemScienceDiscoveryRoute,
  EcosystemUkDirectoryRoute: EcosystemUkDirectoryRoute,
  EcosystemIndexRoute: EcosystemIndexRoute,
}

const EcosystemRouteWithChildren = EcosystemRoute._addFileChildren(
  EcosystemRouteChildren,
)

interface InsightsRouteChildren {
  InsightsEventsRoute: typeof InsightsEventsRoute
  InsightsLongevityNewsRoute: typeof InsightsLongevityNewsRoute
  InsightsResearchHighlightsRoute: typeof InsightsResearchHighlightsRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsEventsRoute: InsightsEventsRoute,
  InsightsLongevityNewsRoute: InsightsLongevityNewsRoute,
  InsightsResearchHighlightsRoute: InsightsResearchHighlightsRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRouteWithChildren,
  EcosystemRoute: EcosystemRouteWithChildren,
  FounderRoute: FounderRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PublicationsSlugRoute: PublicationsSlugRoute,
  PublicationsIndexRoute: PublicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
