/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollaborateRouteImport } from './routes/collaborate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ParticipateRouteImport } from './routes/participate'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as CollaborateIndexRouteImport } from './routes/collaborate.index'
import { Route as CollaborateOpportunitiesRouteImport } from './routes/collaborate.opportunities'
import { Route as CollaboratePartnersRouteImport } from './routes/collaborate.partners'
import { Route as CollaborateProjectsRouteImport } from './routes/collaborate.projects'
import { Route as CollaborateTranslationInnovationRouteImport } from './routes/collaborate.translation-innovation'
import { Route as DiscoverIndexRouteImport } from './routes/discover.index'
import { Route as DiscoverBiologyOfAgingRouteImport } from './routes/discover.biology-of-aging'
import { Route as DiscoverHealthyLongevityRouteImport } from './routes/discover.healthy-longevity'
import { Route as DiscoverScientificMissionsRouteImport } from './routes/discover.scientific-missions'
import { Route as EcosystemIndexRouteImport } from './routes/ecosystem.index'
import { Route as EcosystemClinicalValidationRouteImport } from './routes/ecosystem.clinical-validation'
import { Route as EcosystemInvestmentCommercialRouteImport } from './routes/ecosystem.investment-commercial'
import { Route as EcosystemManufacturingSupplyRouteImport } from './routes/ecosystem.manufacturing-supply'
import { Route as EcosystemScienceDiscoveryRouteImport } from './routes/ecosystem.science-discovery'
import { Route as EcosystemUkDirectoryRouteImport } from './routes/ecosystem.uk-directory'
import { Route as ParticipateIndexRouteImport } from './routes/participate.index'
import { Route as ParticipateCommunityRouteImport } from './routes/participate.community'
import { Route as ParticipateEventsRouteImport } from './routes/participate.events'
import { Route as ParticipateMembersRouteImport } from './routes/participate.members'
import { Route as ParticipateNewsRouteImport } from './routes/participate.news'
import { Route as PublicationsIndexRouteImport } from './routes/publications.index'
import { Route as PublicationsSlugRouteImport } from './routes/publications.$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsChronicDiseasePreventionRouteImport } from './routes/solutions.chronic-disease-prevention'
import { Route as SolutionsLongevityHealthManagementRouteImport } from './routes/solutions.longevity-health-management'
import { Route as SolutionsMedicalAestheticsRouteImport } from './routes/solutions.medical-aesthetics'
import { Route as SolutionsPersonalisedMedicineRouteImport } from './routes/solutions.personalised-medicine'
import { Route as SolutionsProductsRouteImport } from './routes/solutions.products'
import { Route as SolutionsRegenerativeMedicineRouteImport } from './routes/solutions.regenerative-medicine'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedMembersProfileIdRouteImport } from './routes/_authenticated/members.$profileId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateRoute = CollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipateRoute = ParticipateRouteImport.update({
  id: '/participate',
  path: '/participate',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CollaborateIndexRoute = CollaborateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollaborateRoute,
} as any)
const CollaborateOpportunitiesRoute =
  CollaborateOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => CollaborateRoute,
  } as any)
const CollaboratePartnersRoute = CollaboratePartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => CollaborateRoute,
} as any)
const CollaborateProjectsRoute = CollaborateProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => CollaborateRoute,
} as any)
const CollaborateTranslationInnovationRoute =
  CollaborateTranslationInnovationRouteImport.update({
    id: '/translation-innovation',
    path: '/translation-innovation',
    getParentRoute: () => CollaborateRoute,
  } as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiscoverRoute,
} as any)
const DiscoverBiologyOfAgingRoute = DiscoverBiologyOfAgingRouteImport.update({
  id: '/biology-of-aging',
  path: '/biology-of-aging',
  getParentRoute: () => DiscoverRoute,
} as any)
const DiscoverHealthyLongevityRoute =
  DiscoverHealthyLongevityRouteImport.update({
    id: '/healthy-longevity',
    path: '/healthy-longevity',
    getParentRoute: () => DiscoverRoute,
  } as any)
const DiscoverScientificMissionsRoute =
  DiscoverScientificMissionsRouteImport.update({
    id: '/scientific-missions',
    path: '/scientific-missions',
    getParentRoute: () => DiscoverRoute,
  } as any)
const EcosystemIndexRoute = EcosystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcosystemRoute,
} as any)
const EcosystemClinicalValidationRoute =
  EcosystemClinicalValidationRouteImport.update({
    id: '/clinical-validation',
    path: '/clinical-validation',
    getParentRoute: () => EcosystemRoute,
  } as any)
const EcosystemInvestmentCommercialRoute =
  EcosystemInvestmentCommercialRouteImport.update({
    id: '/investment-commercial',
    path: '/investment-commercial',
    getParentRoute: () => EcosystemRoute,
  } as any)
const EcosystemManufacturingSupplyRoute =
  EcosystemManufacturingSupplyRouteImport.update({
    id: '/manufacturing-supply',
    path: '/manufacturing-supply',
    getParentRoute: () => EcosystemRoute,
  } as any)
const EcosystemScienceDiscoveryRoute =
  EcosystemScienceDiscoveryRouteImport.update({
    id: '/science-discovery',
    path: '/science-discovery',
    getParentRoute: () => EcosystemRoute,
  } as any)
const EcosystemUkDirectoryRoute = EcosystemUkDirectoryRouteImport.update({
  id: '/uk-directory',
  path: '/uk-directory',
  getParentRoute: () => EcosystemRoute,
} as any)
const ParticipateIndexRoute = ParticipateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParticipateRoute,
} as any)
const ParticipateCommunityRoute = ParticipateCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => ParticipateRoute,
} as any)
const ParticipateEventsRoute = ParticipateEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ParticipateRoute,
} as any)
const ParticipateMembersRoute = ParticipateMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ParticipateRoute,
} as any)
const ParticipateNewsRoute = ParticipateNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ParticipateRoute,
} as any)
const PublicationsIndexRoute = PublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsSlugRoute = PublicationsSlugRouteImport.update({
  id: '/publications/$slug',
  path: '/publications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsChronicDiseasePreventionRoute =
  SolutionsChronicDiseasePreventionRouteImport.update({
    id: '/chronic-disease-prevention',
    path: '/chronic-disease-prevention',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsLongevityHealthManagementRoute =
  SolutionsLongevityHealthManagementRouteImport.update({
    id: '/longevity-health-management',
    path: '/longevity-health-management',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsMedicalAestheticsRoute =
  SolutionsMedicalAestheticsRouteImport.update({
    id: '/medical-aesthetics',
    path: '/medical-aesthetics',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsPersonalisedMedicineRoute =
  SolutionsPersonalisedMedicineRouteImport.update({
    id: '/personalised-medicine',
    path: '/personalised-medicine',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsProductsRoute = SolutionsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsRegenerativeMedicineRoute =
  SolutionsRegenerativeMedicineRouteImport.update({
    id: '/regenerative-medicine',
    path: '/regenerative-medicine',
    getParentRoute: () => SolutionsRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersProfileIdRoute =
  AuthenticatedMembersProfileIdRouteImport.update({
    id: '/members/$profileId',
    path: '/members/$profileId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/collaborate': typeof CollaborateRouteWithChildren
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/ecosystem': typeof EcosystemRouteWithChildren
  '/founder': typeof FounderRoute
  '/participate': typeof ParticipateRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/collaborate/opportunities': typeof CollaborateOpportunitiesRoute
  '/collaborate/partners': typeof CollaboratePartnersRoute
  '/collaborate/projects': typeof CollaborateProjectsRoute
  '/collaborate/translation-innovation': typeof CollaborateTranslationInnovationRoute
  '/discover/biology-of-aging': typeof DiscoverBiologyOfAgingRoute
  '/discover/healthy-longevity': typeof DiscoverHealthyLongevityRoute
  '/discover/scientific-missions': typeof DiscoverScientificMissionsRoute
  '/ecosystem/clinical-validation': typeof EcosystemClinicalValidationRoute
  '/ecosystem/investment-commercial': typeof EcosystemInvestmentCommercialRoute
  '/ecosystem/manufacturing-supply': typeof EcosystemManufacturingSupplyRoute
  '/ecosystem/science-discovery': typeof EcosystemScienceDiscoveryRoute
  '/ecosystem/uk-directory': typeof EcosystemUkDirectoryRoute
  '/participate/community': typeof ParticipateCommunityRoute
  '/participate/events': typeof ParticipateEventsRoute
  '/participate/members': typeof ParticipateMembersRoute
  '/participate/news': typeof ParticipateNewsRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/solutions/chronic-disease-prevention': typeof SolutionsChronicDiseasePreventionRoute
  '/solutions/longevity-health-management': typeof SolutionsLongevityHealthManagementRoute
  '/solutions/medical-aesthetics': typeof SolutionsMedicalAestheticsRoute
  '/solutions/personalised-medicine': typeof SolutionsPersonalisedMedicineRoute
  '/solutions/products': typeof SolutionsProductsRoute
  '/solutions/regenerative-medicine': typeof SolutionsRegenerativeMedicineRoute
  '/collaborate/': typeof CollaborateIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/ecosystem/': typeof EcosystemIndexRoute
  '/participate/': typeof ParticipateIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/members/$profileId': typeof AuthenticatedMembersProfileIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/collaborate/opportunities': typeof CollaborateOpportunitiesRoute
  '/collaborate/partners': typeof CollaboratePartnersRoute
  '/collaborate/projects': typeof CollaborateProjectsRoute
  '/collaborate/translation-innovation': typeof CollaborateTranslationInnovationRoute
  '/discover/biology-of-aging': typeof DiscoverBiologyOfAgingRoute
  '/discover/healthy-longevity': typeof DiscoverHealthyLongevityRoute
  '/discover/scientific-missions': typeof DiscoverScientificMissionsRoute
  '/ecosystem/clinical-validation': typeof EcosystemClinicalValidationRoute
  '/ecosystem/investment-commercial': typeof EcosystemInvestmentCommercialRoute
  '/ecosystem/manufacturing-supply': typeof EcosystemManufacturingSupplyRoute
  '/ecosystem/science-discovery': typeof EcosystemScienceDiscoveryRoute
  '/ecosystem/uk-directory': typeof EcosystemUkDirectoryRoute
  '/participate/community': typeof ParticipateCommunityRoute
  '/participate/events': typeof ParticipateEventsRoute
  '/participate/members': typeof ParticipateMembersRoute
  '/participate/news': typeof ParticipateNewsRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/solutions/chronic-disease-prevention': typeof SolutionsChronicDiseasePreventionRoute
  '/solutions/longevity-health-management': typeof SolutionsLongevityHealthManagementRoute
  '/solutions/medical-aesthetics': typeof SolutionsMedicalAestheticsRoute
  '/solutions/personalised-medicine': typeof SolutionsPersonalisedMedicineRoute
  '/solutions/products': typeof SolutionsProductsRoute
  '/solutions/regenerative-medicine': typeof SolutionsRegenerativeMedicineRoute
  '/collaborate': typeof CollaborateIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/ecosystem': typeof EcosystemIndexRoute
  '/participate': typeof ParticipateIndexRoute
  '/publications': typeof PublicationsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/members/$profileId': typeof AuthenticatedMembersProfileIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/collaborate': typeof CollaborateRouteWithChildren
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/ecosystem': typeof EcosystemRouteWithChildren
  '/founder': typeof FounderRoute
  '/participate': typeof ParticipateRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/collaborate/opportunities': typeof CollaborateOpportunitiesRoute
  '/collaborate/partners': typeof CollaboratePartnersRoute
  '/collaborate/projects': typeof CollaborateProjectsRoute
  '/collaborate/translation-innovation': typeof CollaborateTranslationInnovationRoute
  '/discover/biology-of-aging': typeof DiscoverBiologyOfAgingRoute
  '/discover/healthy-longevity': typeof DiscoverHealthyLongevityRoute
  '/discover/scientific-missions': typeof DiscoverScientificMissionsRoute
  '/ecosystem/clinical-validation': typeof EcosystemClinicalValidationRoute
  '/ecosystem/investment-commercial': typeof EcosystemInvestmentCommercialRoute
  '/ecosystem/manufacturing-supply': typeof EcosystemManufacturingSupplyRoute
  '/ecosystem/science-discovery': typeof EcosystemScienceDiscoveryRoute
  '/ecosystem/uk-directory': typeof EcosystemUkDirectoryRoute
  '/participate/community': typeof ParticipateCommunityRoute
  '/participate/events': typeof ParticipateEventsRoute
  '/participate/members': typeof ParticipateMembersRoute
  '/participate/news': typeof ParticipateNewsRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/solutions/chronic-disease-prevention': typeof SolutionsChronicDiseasePreventionRoute
  '/solutions/longevity-health-management': typeof SolutionsLongevityHealthManagementRoute
  '/solutions/medical-aesthetics': typeof SolutionsMedicalAestheticsRoute
  '/solutions/personalised-medicine': typeof SolutionsPersonalisedMedicineRoute
  '/solutions/products': typeof SolutionsProductsRoute
  '/solutions/regenerative-medicine': typeof SolutionsRegenerativeMedicineRoute
  '/collaborate/': typeof CollaborateIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/ecosystem/': typeof EcosystemIndexRoute
  '/participate/': typeof ParticipateIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/_authenticated/members/$profileId': typeof AuthenticatedMembersProfileIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/collaborate'
    | '/contact'
    | '/discover'
    | '/ecosystem'
    | '/founder'
    | '/participate'
    | '/privacy'
    | '/solutions'
    | '/dashboard'
    | '/profile'
    | '/collaborate/opportunities'
    | '/collaborate/partners'
    | '/collaborate/projects'
    | '/collaborate/translation-innovation'
    | '/discover/biology-of-aging'
    | '/discover/healthy-longevity'
    | '/discover/scientific-missions'
    | '/ecosystem/clinical-validation'
    | '/ecosystem/investment-commercial'
    | '/ecosystem/manufacturing-supply'
    | '/ecosystem/science-discovery'
    | '/ecosystem/uk-directory'
    | '/participate/community'
    | '/participate/events'
    | '/participate/members'
    | '/participate/news'
    | '/publications/$slug'
    | '/solutions/chronic-disease-prevention'
    | '/solutions/longevity-health-management'
    | '/solutions/medical-aesthetics'
    | '/solutions/personalised-medicine'
    | '/solutions/products'
    | '/solutions/regenerative-medicine'
    | '/collaborate/'
    | '/discover/'
    | '/ecosystem/'
    | '/participate/'
    | '/publications/'
    | '/solutions/'
    | '/members/$profileId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/members/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/founder'
    | '/privacy'
    | '/dashboard'
    | '/profile'
    | '/collaborate/opportunities'
    | '/collaborate/partners'
    | '/collaborate/projects'
    | '/collaborate/translation-innovation'
    | '/discover/biology-of-aging'
    | '/discover/healthy-longevity'
    | '/discover/scientific-missions'
    | '/ecosystem/clinical-validation'
    | '/ecosystem/investment-commercial'
    | '/ecosystem/manufacturing-supply'
    | '/ecosystem/science-discovery'
    | '/ecosystem/uk-directory'
    | '/participate/community'
    | '/participate/events'
    | '/participate/members'
    | '/participate/news'
    | '/publications/$slug'
    | '/solutions/chronic-disease-prevention'
    | '/solutions/longevity-health-management'
    | '/solutions/medical-aesthetics'
    | '/solutions/personalised-medicine'
    | '/solutions/products'
    | '/solutions/regenerative-medicine'
    | '/collaborate'
    | '/discover'
    | '/ecosystem'
    | '/participate'
    | '/publications'
    | '/solutions'
    | '/members/$profileId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/members'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/collaborate'
    | '/contact'
    | '/discover'
    | '/ecosystem'
    | '/founder'
    | '/participate'
    | '/privacy'
    | '/solutions'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/collaborate/opportunities'
    | '/collaborate/partners'
    | '/collaborate/projects'
    | '/collaborate/translation-innovation'
    | '/discover/biology-of-aging'
    | '/discover/healthy-longevity'
    | '/discover/scientific-missions'
    | '/ecosystem/clinical-validation'
    | '/ecosystem/investment-commercial'
    | '/ecosystem/manufacturing-supply'
    | '/ecosystem/science-discovery'
    | '/ecosystem/uk-directory'
    | '/participate/community'
    | '/participate/events'
    | '/participate/members'
    | '/participate/news'
    | '/publications/$slug'
    | '/solutions/chronic-disease-prevention'
    | '/solutions/longevity-health-management'
    | '/solutions/medical-aesthetics'
    | '/solutions/personalised-medicine'
    | '/solutions/products'
    | '/solutions/regenerative-medicine'
    | '/collaborate/'
    | '/discover/'
    | '/ecosystem/'
    | '/participate/'
    | '/publications/'
    | '/solutions/'
    | '/_authenticated/members/$profileId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/members/'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CollaborateRoute: typeof CollaborateRouteWithChildren
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRouteWithChildren
  EcosystemRoute: typeof EcosystemRouteWithChildren
  FounderRoute: typeof FounderRoute
  ParticipateRoute: typeof ParticipateRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  PublicationsSlugRoute: typeof PublicationsSlugRoute
  PublicationsIndexRoute: typeof PublicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborate': {
      id: '/collaborate'
      path: '/collaborate'
      fullPath: '/collaborate'
      preLoaderRoute: typeof CollaborateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participate': {
      id: '/participate'
      path: '/participate'
      fullPath: '/participate'
      preLoaderRoute: typeof ParticipateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/collaborate/': {
      id: '/collaborate/'
      path: '/'
      fullPath: '/collaborate/'
      preLoaderRoute: typeof CollaborateIndexRouteImport
      parentRoute: typeof CollaborateRoute
    }
    '/collaborate/opportunities': {
      id: '/collaborate/opportunities'
      path: '/opportunities'
      fullPath: '/collaborate/opportunities'
      preLoaderRoute: typeof CollaborateOpportunitiesRouteImport
      parentRoute: typeof CollaborateRoute
    }
    '/collaborate/partners': {
      id: '/collaborate/partners'
      path: '/partners'
      fullPath: '/collaborate/partners'
      preLoaderRoute: typeof CollaboratePartnersRouteImport
      parentRoute: typeof CollaborateRoute
    }
    '/collaborate/projects': {
      id: '/collaborate/projects'
      path: '/projects'
      fullPath: '/collaborate/projects'
      preLoaderRoute: typeof CollaborateProjectsRouteImport
      parentRoute: typeof CollaborateRoute
    }
    '/collaborate/translation-innovation': {
      id: '/collaborate/translation-innovation'
      path: '/translation-innovation'
      fullPath: '/collaborate/translation-innovation'
      preLoaderRoute: typeof CollaborateTranslationInnovationRouteImport
      parentRoute: typeof CollaborateRoute
    }
    '/discover/': {
      id: '/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/discover/biology-of-aging': {
      id: '/discover/biology-of-aging'
      path: '/biology-of-aging'
      fullPath: '/discover/biology-of-aging'
      preLoaderRoute: typeof DiscoverBiologyOfAgingRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/discover/healthy-longevity': {
      id: '/discover/healthy-longevity'
      path: '/healthy-longevity'
      fullPath: '/discover/healthy-longevity'
      preLoaderRoute: typeof DiscoverHealthyLongevityRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/discover/scientific-missions': {
      id: '/discover/scientific-missions'
      path: '/scientific-missions'
      fullPath: '/discover/scientific-missions'
      preLoaderRoute: typeof DiscoverScientificMissionsRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/ecosystem/': {
      id: '/ecosystem/'
      path: '/'
      fullPath: '/ecosystem/'
      preLoaderRoute: typeof EcosystemIndexRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/clinical-validation': {
      id: '/ecosystem/clinical-validation'
      path: '/clinical-validation'
      fullPath: '/ecosystem/clinical-validation'
      preLoaderRoute: typeof EcosystemClinicalValidationRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/investment-commercial': {
      id: '/ecosystem/investment-commercial'
      path: '/investment-commercial'
      fullPath: '/ecosystem/investment-commercial'
      preLoaderRoute: typeof EcosystemInvestmentCommercialRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/manufacturing-supply': {
      id: '/ecosystem/manufacturing-supply'
      path: '/manufacturing-supply'
      fullPath: '/ecosystem/manufacturing-supply'
      preLoaderRoute: typeof EcosystemManufacturingSupplyRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/science-discovery': {
      id: '/ecosystem/science-discovery'
      path: '/science-discovery'
      fullPath: '/ecosystem/science-discovery'
      preLoaderRoute: typeof EcosystemScienceDiscoveryRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/uk-directory': {
      id: '/ecosystem/uk-directory'
      path: '/uk-directory'
      fullPath: '/ecosystem/uk-directory'
      preLoaderRoute: typeof EcosystemUkDirectoryRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/participate/': {
      id: '/participate/'
      path: '/'
      fullPath: '/participate/'
      preLoaderRoute: typeof ParticipateIndexRouteImport
      parentRoute: typeof ParticipateRoute
    }
    '/participate/community': {
      id: '/participate/community'
      path: '/community'
      fullPath: '/participate/community'
      preLoaderRoute: typeof ParticipateCommunityRouteImport
      parentRoute: typeof ParticipateRoute
    }
    '/participate/events': {
      id: '/participate/events'
      path: '/events'
      fullPath: '/participate/events'
      preLoaderRoute: typeof ParticipateEventsRouteImport
      parentRoute: typeof ParticipateRoute
    }
    '/participate/members': {
      id: '/participate/members'
      path: '/members'
      fullPath: '/participate/members'
      preLoaderRoute: typeof ParticipateMembersRouteImport
      parentRoute: typeof ParticipateRoute
    }
    '/participate/news': {
      id: '/participate/news'
      path: '/news'
      fullPath: '/participate/news'
      preLoaderRoute: typeof ParticipateNewsRouteImport
      parentRoute: typeof ParticipateRoute
    }
    '/publications/': {
      id: '/publications/'
      path: '/publications'
      fullPath: '/publications/'
      preLoaderRoute: typeof PublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$slug': {
      id: '/publications/$slug'
      path: '/publications/$slug'
      fullPath: '/publications/$slug'
      preLoaderRoute: typeof PublicationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/chronic-disease-prevention': {
      id: '/solutions/chronic-disease-prevention'
      path: '/chronic-disease-prevention'
      fullPath: '/solutions/chronic-disease-prevention'
      preLoaderRoute: typeof SolutionsChronicDiseasePreventionRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/longevity-health-management': {
      id: '/solutions/longevity-health-management'
      path: '/longevity-health-management'
      fullPath: '/solutions/longevity-health-management'
      preLoaderRoute: typeof SolutionsLongevityHealthManagementRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/medical-aesthetics': {
      id: '/solutions/medical-aesthetics'
      path: '/medical-aesthetics'
      fullPath: '/solutions/medical-aesthetics'
      preLoaderRoute: typeof SolutionsMedicalAestheticsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/personalised-medicine': {
      id: '/solutions/personalised-medicine'
      path: '/personalised-medicine'
      fullPath: '/solutions/personalised-medicine'
      preLoaderRoute: typeof SolutionsPersonalisedMedicineRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/products': {
      id: '/solutions/products'
      path: '/products'
      fullPath: '/solutions/products'
      preLoaderRoute: typeof SolutionsProductsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/regenerative-medicine': {
      id: '/solutions/regenerative-medicine'
      path: '/regenerative-medicine'
      fullPath: '/solutions/regenerative-medicine'
      preLoaderRoute: typeof SolutionsRegenerativeMedicineRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$profileId': {
      id: '/_authenticated/members/$profileId'
      path: '/members/$profileId'
      fullPath: '/members/$profileId'
      preLoaderRoute: typeof AuthenticatedMembersProfileIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMembersProfileIdRoute: typeof AuthenticatedMembersProfileIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMembersProfileIdRoute: AuthenticatedMembersProfileIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CollaborateRouteChildren {
  CollaborateOpportunitiesRoute: typeof CollaborateOpportunitiesRoute
  CollaboratePartnersRoute: typeof CollaboratePartnersRoute
  CollaborateProjectsRoute: typeof CollaborateProjectsRoute
  CollaborateTranslationInnovationRoute: typeof CollaborateTranslationInnovationRoute
  CollaborateIndexRoute: typeof CollaborateIndexRoute
}

const CollaborateRouteChildren: CollaborateRouteChildren = {
  CollaborateOpportunitiesRoute: CollaborateOpportunitiesRoute,
  CollaboratePartnersRoute: CollaboratePartnersRoute,
  CollaborateProjectsRoute: CollaborateProjectsRoute,
  CollaborateTranslationInnovationRoute: CollaborateTranslationInnovationRoute,
  CollaborateIndexRoute: CollaborateIndexRoute,
}

const CollaborateRouteWithChildren = CollaborateRoute._addFileChildren(
  CollaborateRouteChildren,
)

interface DiscoverRouteChildren {
  DiscoverBiologyOfAgingRoute: typeof DiscoverBiologyOfAgingRoute
  DiscoverHealthyLongevityRoute: typeof DiscoverHealthyLongevityRoute
  DiscoverScientificMissionsRoute: typeof DiscoverScientificMissionsRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
}

const DiscoverRouteChildren: DiscoverRouteChildren = {
  DiscoverBiologyOfAgingRoute: DiscoverBiologyOfAgingRoute,
  DiscoverHealthyLongevityRoute: DiscoverHealthyLongevityRoute,
  DiscoverScientificMissionsRoute: DiscoverScientificMissionsRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
}

const DiscoverRouteWithChildren = DiscoverRoute._addFileChildren(
  DiscoverRouteChildren,
)

interface EcosystemRouteChildren {
  EcosystemClinicalValidationRoute: typeof EcosystemClinicalValidationRoute
  EcosystemInvestmentCommercialRoute: typeof EcosystemInvestmentCommercialRoute
  EcosystemManufacturingSupplyRoute: typeof EcosystemManufacturingSupplyRoute
  EcosystemScienceDiscoveryRoute: typeof EcosystemScienceDiscoveryRoute
  EcosystemUkDirectoryRoute: typeof EcosystemUkDirectoryRoute
  EcosystemIndexRoute: typeof EcosystemIndexRoute
}

const EcosystemRouteChildren: EcosystemRouteChildren = {
  EcosystemClinicalValidationRoute: EcosystemClinicalValidationRoute,
  EcosystemInvestmentCommercialRoute: EcosystemInvestmentCommercialRoute,
  EcosystemManufacturingSupplyRoute: EcosystemManufacturingSupplyRoute,
  EcosystemScienceDiscoveryRoute: EcosystemScienceDiscoveryRoute,
  EcosystemUkDirectoryRoute: EcosystemUkDirectoryRoute,
  EcosystemIndexRoute: EcosystemIndexRoute,
}

const EcosystemRouteWithChildren = EcosystemRoute._addFileChildren(
  EcosystemRouteChildren,
)

interface ParticipateRouteChildren {
  ParticipateCommunityRoute: typeof ParticipateCommunityRoute
  ParticipateEventsRoute: typeof ParticipateEventsRoute
  ParticipateMembersRoute: typeof ParticipateMembersRoute
  ParticipateNewsRoute: typeof ParticipateNewsRoute
  ParticipateIndexRoute: typeof ParticipateIndexRoute
}

const ParticipateRouteChildren: ParticipateRouteChildren = {
  ParticipateCommunityRoute: ParticipateCommunityRoute,
  ParticipateEventsRoute: ParticipateEventsRoute,
  ParticipateMembersRoute: ParticipateMembersRoute,
  ParticipateNewsRoute: ParticipateNewsRoute,
  ParticipateIndexRoute: ParticipateIndexRoute,
}

const ParticipateRouteWithChildren = ParticipateRoute._addFileChildren(
  ParticipateRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsChronicDiseasePreventionRoute: typeof SolutionsChronicDiseasePreventionRoute
  SolutionsLongevityHealthManagementRoute: typeof SolutionsLongevityHealthManagementRoute
  SolutionsMedicalAestheticsRoute: typeof SolutionsMedicalAestheticsRoute
  SolutionsPersonalisedMedicineRoute: typeof SolutionsPersonalisedMedicineRoute
  SolutionsProductsRoute: typeof SolutionsProductsRoute
  SolutionsRegenerativeMedicineRoute: typeof SolutionsRegenerativeMedicineRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsChronicDiseasePreventionRoute:
    SolutionsChronicDiseasePreventionRoute,
  SolutionsLongevityHealthManagementRoute:
    SolutionsLongevityHealthManagementRoute,
  SolutionsMedicalAestheticsRoute: SolutionsMedicalAestheticsRoute,
  SolutionsPersonalisedMedicineRoute: SolutionsPersonalisedMedicineRoute,
  SolutionsProductsRoute: SolutionsProductsRoute,
  SolutionsRegenerativeMedicineRoute: SolutionsRegenerativeMedicineRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CollaborateRoute: CollaborateRouteWithChildren,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRouteWithChildren,
  EcosystemRoute: EcosystemRouteWithChildren,
  FounderRoute: FounderRoute,
  ParticipateRoute: ParticipateRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  PublicationsSlugRoute: PublicationsSlugRoute,
  PublicationsIndexRoute: PublicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
