/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as EcosystemIndexRouteImport } from './routes/ecosystem.index'
import { Route as EcosystemClinicalValidationRouteImport } from './routes/ecosystem.clinical-validation'
import { Route as EcosystemScienceDiscoveryRouteImport } from './routes/ecosystem.science-discovery'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedMembersProfileIdRouteImport } from './routes/_authenticated/members.$profileId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EcosystemIndexRoute = EcosystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcosystemRoute,
} as any)
const EcosystemClinicalValidationRoute =
  EcosystemClinicalValidationRouteImport.update({
    id: '/clinical-validation',
    path: '/clinical-validation',
    getParentRoute: () => EcosystemRoute,
  } as any)
const EcosystemScienceDiscoveryRoute =
  EcosystemScienceDiscoveryRouteImport.update({
    id: '/science-discovery',
    path: '/science-discovery',
    getParentRoute: () => EcosystemRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersProfileIdRoute =
  AuthenticatedMembersProfileIdRouteImport.update({
    id: '/members/$profileId',
    path: '/members/$profileId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ecosystem/clinical-validation': typeof EcosystemClinicalValidationRoute
  '/ecosystem/science-discovery': typeof EcosystemScienceDiscoveryRoute
  '/ecosystem/': typeof EcosystemIndexRoute
  '/members/$profileId': typeof AuthenticatedMembersProfileIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ecosystem/clinical-validation': typeof EcosystemClinicalValidationRoute
  '/ecosystem/science-discovery': typeof EcosystemScienceDiscoveryRoute
  '/ecosystem': typeof EcosystemIndexRoute
  '/members/$profileId': typeof AuthenticatedMembersProfileIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/ecosystem/clinical-validation': typeof EcosystemClinicalValidationRoute
  '/ecosystem/science-discovery': typeof EcosystemScienceDiscoveryRoute
  '/ecosystem/': typeof EcosystemIndexRoute
  '/_authenticated/members/$profileId': typeof AuthenticatedMembersProfileIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/discover'
    | '/ecosystem'
    | '/dashboard'
    | '/profile'
    | '/ecosystem/clinical-validation'
    | '/ecosystem/science-discovery'
    | '/ecosystem/'
    | '/members/$profileId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/members/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/discover'
    | '/dashboard'
    | '/profile'
    | '/ecosystem/clinical-validation'
    | '/ecosystem/science-discovery'
    | '/ecosystem'
    | '/members/$profileId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/members'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/discover'
    | '/ecosystem'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/ecosystem/clinical-validation'
    | '/ecosystem/science-discovery'
    | '/ecosystem/'
    | '/_authenticated/members/$profileId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/members/'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  EcosystemRoute: typeof EcosystemRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ecosystem/': {
      id: '/ecosystem/'
      path: '/'
      fullPath: '/ecosystem/'
      preLoaderRoute: typeof EcosystemIndexRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/clinical-validation': {
      id: '/ecosystem/clinical-validation'
      path: '/clinical-validation'
      fullPath: '/ecosystem/clinical-validation'
      preLoaderRoute: typeof EcosystemClinicalValidationRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/ecosystem/science-discovery': {
      id: '/ecosystem/science-discovery'
      path: '/science-discovery'
      fullPath: '/ecosystem/science-discovery'
      preLoaderRoute: typeof EcosystemScienceDiscoveryRouteImport
      parentRoute: typeof EcosystemRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$profileId': {
      id: '/_authenticated/members/$profileId'
      path: '/members/$profileId'
      fullPath: '/members/$profileId'
      preLoaderRoute: typeof AuthenticatedMembersProfileIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMembersProfileIdRoute: typeof AuthenticatedMembersProfileIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMembersProfileIdRoute: AuthenticatedMembersProfileIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EcosystemRouteChildren {
  EcosystemClinicalValidationRoute: typeof EcosystemClinicalValidationRoute
  EcosystemScienceDiscoveryRoute: typeof EcosystemScienceDiscoveryRoute
  EcosystemIndexRoute: typeof EcosystemIndexRoute
}

const EcosystemRouteChildren: EcosystemRouteChildren = {
  EcosystemClinicalValidationRoute: EcosystemClinicalValidationRoute,
  EcosystemScienceDiscoveryRoute: EcosystemScienceDiscoveryRoute,
  EcosystemIndexRoute: EcosystemIndexRoute,
}

const EcosystemRouteWithChildren = EcosystemRoute._addFileChildren(
  EcosystemRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  EcosystemRoute: EcosystemRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
